services:
  app:
    container_name: blog
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGO_USER=root
      - MONGO_PASSWORD=1234
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DATABASE=blog
      - MONGO_URI=mongodb+srv://admin:admin123@guide-cluster.ewwjg.mongodb.net/?retryWrites=true&w=majority&appName=Guide-Cluster
      - JWT_SECRET=d50d1cab322c6f8ba9d82e8765c5e47b0dde58f4b288b24d07c05eca4458e87e40ef773a02434725d020f35eff4a33e0c83c4addd80ec5a7c7a9239b8d137a59
      - JWT_EXPIRATION=86400000
      - JWT_REFRESH_EXPIRATION=604800000
    depends_on:
      - mongodb
    networks:
      - blog-network

volumes:
  mongo-data:
    name: mongo-data

networks:
  blog-network:
    driver: bridge

