version: "3.9"

services:
  mongodb:
    image: mongo:8.0
    container_name: blog-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-secure_password}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-blog}
    volumes:
      - mongodb_data:/data/db
    networks:
      - blog-network

  postgres:
    image: postgres:15
    container_name: blog-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${POSTGRES_USER:-keycloak}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - blog-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.0
    container_name: blog-keycloak
    command: start-dev
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: ${KC_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD:-admin}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: ${POSTGRES_USER:-keycloak}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD:-password}
      KC_HEALTH_ENABLED: "true"
    ports:
      - "9000:8080"
    depends_on:
      - postgres
    networks:
      - blog-network

volumes:
  mongodb_data:
  postgres_data:

networks:
  blog-network:
    driver: bridge
