server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@localhost:27017/${MONGO_DATABASE}?authSource=admin
      database: blog
  jackson:
    modules:
      - com.fasterxml.jackson.datatype:jackson-datatype-jsr310
    serialization:
      write-dates-as-timestamps: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:9000/realms/blog-realm}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:9000/realms/blog-realm/protocol/openid-connect/certs}

keycloak:
  realm: ${KEYCLOAK_REALM:blog-realm}
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:http://localhost:9000}
  ssl-required: external
  resource: ${KEYCLOAK_CLIENT_ID:blog-client}
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET:your-client-secret}
  use-resource-role-mappings: true
  bearer-only: true

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}

logging:
  level:
    com.daviddai.blog: DEBUG
    org.springframework.security: DEBUG
    org.springframework.data.mongodb: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

springdoc:
  api-docs:
    path: /api/docs
  swagger-ui:
    path: /api/docs/ui
    operations-sorter: method
    tags-sorter: alpha
