spring:
  application:
    name: blog
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false
    validate-on-migrate: true
    out-of-order: false
